apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: seldon-server
  namespaceSelector:
    matchNames: []
    any: false
  podMetricsEndpoints:
  - targetPort: 9006
    interval: 15s
    path: /metrics


