apiVersion: mlops.seldon.io/v1alpha1
kind: Server
metadata:
  name: triton-gpu
spec:
  replicas: 7
  serverConfig: triton
  podSpec:
    containers:
    - name: triton
      resources:
        requests:
          nvidia.com/gpu: 1
          memory: 5Gi
          cpu: 5
        limits:
          nvidia.com/gpu: 1
          memory: 50Gi
